config/routes.rb
Rails.application.routes.draw do
  resources :food_items
  get 'home/index'

  get 'home/contact_us'

  get 'home/menu'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  belongs_to :section
end

app/models/section.rb
class Section < ApplicationRecord
    has_many :food_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]

  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :description, :price, :image_url, :section_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contact_us
  end

  def menu
    @sections = Section.all

    if params[:section_id].present?
  		@current_section = Section.find(params[:section_id])
  	end  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/food_items/_form.html.erb
<%= form_with(model: food_item, local: true) do |form| %>
  <% if food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% food_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :food_item_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :food_item_description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :food_item_price %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :food_item_image_url %>
  </div>

  <div class="field">
    <%= form.label :section_id %>
    <%= form.text_field :section_id, id: :food_item_section_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/food_items/edit.html.erb
<h1>Editing Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Food Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Image url</th>
      <th>Section</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= food_item.description %></td>
        <td><%= food_item.price %></td>
        <td><%= food_item.image_url %></td>
        <td><%= food_item.section %></td>
        <td><%= link_to 'Show', food_item %></td>
        <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food Item', new_food_item_path %>

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food_item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @food_item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food_item.price %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @food_item.image_url %>
</p>

<p>
  <strong>Section:</strong>
  <%= @food_item.section %>
</p>

<%= link_to 'Edit', edit_food_item_path(@food_item) %> |
<%= link_to 'Back', food_items_path %>

app/views/home/contact_us.html.erb
<h3>Contact us</h3>

<div class="row">
	<div class="col-sm-4">
		<address>
			Mai's Kitchen <br>
			9039 Bolsa Ave <br>
			Westminster, CA 92683 <br>
			USA <br>
			Tel: 714-765-5423
		</address>
	</div>

	<div class="col-sm-8">
		<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d6635.18368490063!2d-117.971405!3d33.745369!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80dd27caaed9d6b5%3A0x7a376b81b136db84!2s9039+Bolsa+Ave%2C+Westminster%2C+CA+92683!5e0!3m2!1sen!2sus!4v1535790020301" width="500" height="400" frameborder="0" style="border:0" allowfullscreen></iframe>
	</div>

</div>

app/views/home/index.html.erb
<h1>Mai's Kitchen</h1>

<%= link_to 'Menu',home_menu_path, class:'btn btn-primary' %>
<%= link_to 'Contact us', home_contact_us_path, class:'btn btn-primary' %>

app/views/home/menu.html.erb
<div class='container'>
    <% @sections.each do |section| %>
        <ul class="list-group">
            <li class="list-group-item"><%= link_to section.name, home_menu_path(section_id: section.id) %></li>
        </ul>
    <% end %>
</div>


<div class='container'>
    <br>
    <div class="card" style="width: 18rem;">
        <%# @current_section.food_items.each do |item| %>
        <img class="card-img-left" src="<%#= item.image_url %>" alt="">
        <div class="card-body">
            <p class="card-text">
                Name: <%#= item.name %> <br>
                Description: <%#= item.description %> <br>
                Price: <%#= item.price %> <br>
            </p>
        </div>
        <%# end %>
    </div>
   
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coder Restaurant</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarTogglerDemo01">
				<ul class="navbar-nav mr-auto mt-2 mt-lg-0">
					<li class="nav-item active">
						<%= link_to "Home", home_index_path %> 
					</li>
					<li class="nav-item">
						<%= link_to "Menu", home_menu_path %>
					</li>
					<li class="nav-item">
						<%= link_to "Contact us", home_contact_us_path %>
					</li>
				</ul>
			</div>
		</nav>

		<div class="container">
    	<%= yield %>
    <div>
		
  </body>
</html>